name: Newman Automation API Tests by Postman.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #schedule:
  #- cron: '5 6 * * MON-FRI'
  
  workflow_dispatch:
permissions: write-all

jobs:
  automated-api-integracao:
    runs-on: windows-latest
    steps:
        # 1 - Step - Install dependences.
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g newman | 
             npm install -g newman-reporter-htmlextra
             
      # 2 -Step - Run the POSTMAN collection
      - name: Step 2 - Run POSTMAN collection
        if: always()
        continue-on-error: true
        run: |
             newman run Florida_Release_Notes.postman_collection.json -e CI-test.postman_environment.json -r htmlextra --reporter-htmlextra-title "API AUTOMATION - CI Integração pacote 15" --reporter-htmlextra-export testResults/automated_ci_integracao.html --timeout-request 45000 --delay-request 600 --suppress-exit-code
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: testResults
          destination_dir: testResults
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
         connection_url: ${{secrets.MAIL_CONNECTION}}
        # Required mail server address if not connection_url:
         server_address: smtp.gmail.com
        # Server port, default 25:
         server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
         secure: true
        # Optional (recommended) mail server username:
         username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
         password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
         subject: Github Actions test job result
        # Required recipients' addresses:
         to: sauliktest@gmail.com,silvio.aulik@gmail.com
        # Required sender full name (address can be skipped):
         from: sauliktest@gmail.com
        # Optional plain body:
         html_body: <p>Build de Teste Realizado ;) Projeto https://github.com/${{github.repository}} </p><br>
              <p>Link para o Dashboard de Qualidade <a href="https://sauliktest.github.io/api_automation/testResults/index.html">Testes Automatizados</a></p>
         reply_to: silvio.aulik@gmail.com
        # Optional unsigned/invalid certificates allowance:
         ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
         convert_markdown: true
         attachments: ./testResults/*.*
        # Optional priority: 'high', 'normal' (default) or 'low'
         priority: normal
